# Generated by Django 4.1.5 on 2023-01-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_item_todolist_delete_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ToDoList",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.todolist",
            ),
        ),
        migrations.AddField(
            model_name="todolist",
            name="numberOfItems",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="todolist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
