# Generated by Django 4.1.5 on 2023-01-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_item_todolist_todolist_numberofitems_todolist_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="todolist", name="numberOfItems",),
    ]
